// <auto-generated />
using System;
using Bookly.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookly.Infrastructure.Migrations
{
    [DbContext(typeof(BooklyDbContext))]
    partial class BooklyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookly.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Bookly.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaReserva");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("Bookly.Domain.Entities.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TipoServicioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TipoServicioId");

                    b.ToTable("Servicios", (string)null);
                });

            modelBuilder.Entity("Bookly.Domain.Entities.TipoServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TipoServicio", (string)null);
                });

            modelBuilder.Entity("Bookly.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("Bookly.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("Email");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("Bookly.Domain.ValueObjects.FullName", "NombreCompleto", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Apellido");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Nombre");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("Bookly.Domain.ValueObjects.PhoneNumber", "Telefono", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Telefono");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("NombreCompleto")
                        .IsRequired();

                    b.Navigation("Telefono")
                        .IsRequired();
                });

            modelBuilder.Entity("Bookly.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("Bookly.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Bookly.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("Bookly.Domain.Entities.TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("TipoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Bookly.Domain.ValueObjects.Duracion", "Duracion", b1 =>
                        {
                            b1.Property<Guid>("ServicioId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("Value")
                                .HasColumnType("interval")
                                .HasColumnName("Duracion");

                            b1.HasKey("ServicioId");

                            b1.ToTable("Servicios");

                            b1.WithOwner()
                                .HasForeignKey("ServicioId");
                        });

                    b.OwnsOne("Bookly.Domain.ValueObjects.Money", "Precio", b1 =>
                        {
                            b1.Property<Guid>("ServicioId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Precio_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Precio_Currency");

                            b1.HasKey("ServicioId");

                            b1.ToTable("Servicios");

                            b1.WithOwner()
                                .HasForeignKey("ServicioId");
                        });

                    b.OwnsOne("Bookly.Domain.ValueObjects.PoliticaReserva", "PoliticaReserva", b1 =>
                        {
                            b1.Property<Guid>("ServicioId")
                                .HasColumnType("uuid");

                            b1.HasKey("ServicioId");

                            b1.ToTable("Servicios");

                            b1.WithOwner()
                                .HasForeignKey("ServicioId");

                            b1.OwnsOne("Bookly.Domain.ValueObjects.Duracion", "MargenAnticipacion", b2 =>
                                {
                                    b2.Property<Guid>("PoliticaReservaServicioId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("Value")
                                        .HasColumnType("interval")
                                        .HasColumnName("MargenAnticipacion");

                                    b2.HasKey("PoliticaReservaServicioId");

                                    b2.ToTable("Servicios");

                                    b2.WithOwner()
                                        .HasForeignKey("PoliticaReservaServicioId");
                                });

                            b1.OwnsOne("Bookly.Domain.ValueObjects.Duracion", "MargenCancelacion", b2 =>
                                {
                                    b2.Property<Guid>("PoliticaReservaServicioId")
                                        .HasColumnType("uuid");

                                    b2.Property<TimeSpan>("Value")
                                        .HasColumnType("interval")
                                        .HasColumnName("MargenCancelacion");

                                    b2.HasKey("PoliticaReservaServicioId");

                                    b2.ToTable("Servicios");

                                    b2.WithOwner()
                                        .HasForeignKey("PoliticaReservaServicioId");
                                });

                            b1.Navigation("MargenAnticipacion")
                                .IsRequired();

                            b1.Navigation("MargenCancelacion")
                                .IsRequired();
                        });

                    b.Navigation("Duracion")
                        .IsRequired();

                    b.Navigation("PoliticaReserva")
                        .IsRequired();

                    b.Navigation("Precio")
                        .IsRequired();

                    b.Navigation("TipoServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
