services:

  postgres:
    image: postgres:17

    container_name: bookly-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bookly123!
      POSTGRES_DB: bookly

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: